name: maven-publish-jdk8
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven
          server-id: central
          server-username: CENTRAL_USER
          server-password: CENTRAL_PASSWD
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: GPG_PASSPHRASE
      - name: Maven deploy
        run: mvn -U deploy -Prelease
        env:
          CENTRAL_USER: ${{ secrets.CENTRAL_USER }}
          CENTRAL_PASSWD: ${{ secrets.CENTRAL_PASSWD }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
